import { v4 as uuidv4 } from 'uuid';
import {Question} from "../types/Question";

export const questionsList: Question[] = [
  {
    id: uuidv4(),
    title: 'Вопрос 1',
    description: 'описание вопроса',
    theme: 'russian',
    subTheme: '',
    createdAt: Date.now(),
    user: {
      firstName: '',
      lastName: '',
      id: uuidv4(),
      avatar: '',
      phone: '',
      answers: 0,
      questions: 0,
      role: '',
    },
    coast: 0,
    status: '',
    time: 0,
    urgently: false,
  },
  {
    id: uuidv4(),
    title: 'Вопрос 2',
    description: 'описание вопроса',
    theme: 'art',
    subTheme: '',
    createdAt: Date.now(),
    user: {
      firstName: '',
      lastName: '',
      id: uuidv4(),
      avatar: '',
      phone: '',
      answers: 0,
      questions: 0,
      role: '',
    },
    coast: 0,
    status: '',
    time: 0,
    urgently: false,
  },
  {
    id: uuidv4(),
    title: 'Вопрос 3',
    description: 'описание вопроса',
    theme: 'physic',
    subTheme: '',
    createdAt: Date.now(),
    user: {
      firstName: '',
      lastName: '',
      id: uuidv4(),
      avatar: '',
      phone: '',
      answers: 0,
      questions: 0,
      role: '',
    },
    coast: 0,
    status: '',
    time: 0,
    urgently: false,
  },
  {
    id: uuidv4(),
    title: 'Вопрос 4',
    description: 'описание вопроса',
    theme: 'informatics',
    subTheme: '',
    createdAt: Date.now(),
    user: {
      firstName: '',
      lastName: '',
      id: uuidv4(),
      avatar: '',
      phone: '',
      answers: 0,
      questions: 0,
      role: '',
    },
    coast: 0,
    status: '',
    time: 0,
    urgently: false,
  },
  {
    id: uuidv4(),
    title: 'Вопрос 5',
    description: 'описание вопроса',
    theme: 'literature',
    subTheme: '',
    createdAt: Date.now(),
    user: {
      firstName: '',
      lastName: '',
      id: uuidv4(),
      avatar: '',
      phone: '',
      answers: 0,
      questions: 0,
      role: '',
    },
    coast: 0,
    status: '',
    time: 0,
    urgently: false,
  },
  {
    id: uuidv4(),
    title: 'Вопрос 6',
    description: 'описание вопроса',
    theme: 'math',
    subTheme: '',
    createdAt: Date.now(),
    user: {
      firstName: '',
      lastName: '',
      id: uuidv4(),
      avatar: '',
      phone: '',
      answers: 0,
      questions: 0,
      role: '',
    },
    coast: 0,
    status: '',
    time: 0,
    urgently: false,
  }
];