import {UserType} from "../types/UserType";

export const users: UserType[] = [
  {
    firstName: 'Имя пользователя 111',
    lastName: '',
    id: '111',
    avatar: '',
    phone: '',
    answers: 0,
    questions: 0,
    role: '',
  },
  {
    firstName: 'Имя пользователя 222',
    lastName: '',
    id: '222',
    avatar: '',
    phone: '',
    answers: 0,
    questions: 0,
    role: '',
  },
  {
    firstName: 'Имя пользователя 333',
    lastName: '',
    id: '333',
    avatar: '',
    phone: '',
    answers: 0,
    questions: 0,
    role: '',
  },
  {
    firstName: 'Имя пользователя 444',
    lastName: '',
    id: '444',
    avatar: '',
    phone: '',
    answers: 0,
    questions: 0,
    role: '',
  },
  {
    firstName: 'Имя пользователя 555',
    lastName: '',
    id: '555',
    avatar: '',
    phone: '',
    answers: 0,
    questions: 0,
    role: '',
  },
  {
    firstName: 'Имя пользователя 666',
    lastName: '',
    id: '666',
    avatar: '',
    phone: '',
    answers: 0,
    questions: 0,
    role: '',
  },
];