import { UserType } from "../types/UserType";

export const users: UserType[] = [
  {
    firstName: "Имя",
    lastName: "Фамилия",
    id: "111",
    avatar:
      "https://im0-tub-ru.yandex.net/i?id=cb0ef2ded5c53f212c2f36fa49a5c987&n=13&exp=1",
    phone: "89999999999",
    answers: 500,
    questions: 5,
    role: "ADMIN",
    patronymic: "Отчество",
    education: "Я учусь в ВУЗе",
    emailNotify: true,
    balance: 1500,
  },
  {
    firstName: "Имя пользователя 222",
    lastName: "",
    id: "222",
    avatar: "",
    phone: "",
    answers: 0,
    questions: 0,
    role: "",
    patronymic: "",
    balance: 0,
    education: "uni",
    emailNotify: true,
  },
  {
    firstName: "Имя пользователя 333",
    lastName: "",
    id: "333",
    avatar: "",
    phone: "",
    answers: 0,
    questions: 0,
    role: "",
    patronymic: "",
    balance: 0,
    education: "uni",
    emailNotify: true,
  },
  {
    firstName: "Имя пользователя 444",
    lastName: "",
    id: "444",
    avatar: "",
    phone: "",
    answers: 0,
    questions: 0,
    role: "",
    patronymic: "",
    balance: 0,
    education: "uni",
    emailNotify: true,
  },
  {
    firstName: "Имя пользователя 555",
    lastName: "",
    id: "555",
    avatar: "",
    phone: "",
    answers: 0,
    questions: 0,
    role: "",
    patronymic: "",
    balance: 0,
    education: "uni",
    emailNotify: true,
  },
  {
    firstName: "Имя пользователя 666",
    lastName: "",
    id: "666",
    avatar: "",
    phone: "",
    answers: 0,
    questions: 0,
    role: "",
    patronymic: "",
    balance: 0,
    education: "uni",
    emailNotify: true,
  },
];
